// Command gen-config 从 config/*.csv 确定性生成 Go/JS 作物配置。
//
// 用法（仓库根目录）:
//
//	go run ./tools/gen-config -root .
//
// CSV 行序 = 客户端展示/解锁顺序；id 列 = 协议 numeric ID（可与行序解耦）。
// Go 表按 ID 升序索引；JS CROPS 保持 CSV 行序；映射对象按显式 ID。
package main

import (
	"bytes"
	"encoding/csv"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

const goHeader = `// Code generated by tools/gen-config; DO NOT EDIT.
// Source: config/crops.csv
package gameconfig

// CropCount 是已登记作物种数（不含 ID 0）。
const CropCount = {{.Count}}

// cropTable 按下标 id-1 存放，ID 集合恰为 1..CropCount。
var cropTable = []CropConf{
{{- range .ByID}}
	{ID: {{.ID}}, Slug: {{printf "%q" .Slug}}, Name: {{printf "%q" .Name}}, UnlockLevel: {{.UnlockLevel}}, SeedPrice: {{.SeedPrice}}, FruitPrice: {{.FruitPrice}}, Yield: {{.Yield}}, Seasons: {{.Seasons}}, CycleMinutes: {{.CycleMinutes}}, HarvestExp: {{.HarvestExp}}, Hidden: {{.Hidden}}, DropLevel: {{.DropLevel}}},
{{- end}}
}
`

const jsHeader = `// Code generated by tools/gen-config; DO NOT EDIT.
// Source: config/crops.csv
// CROPS 数组顺序 = 策划展示顺序；numeric ID 见 CROP_*_TO_* 映射（可与数组下标解耦）。

/** @type {Array<{ id: string, name: string, unlock: number, seedPrice: number, seasons: number, cycleMinutes: number, cycleH: number, yield: number, fruitPrice: number, harvestExp: number, body: string, color: string, fruit: number, leaf: number, hidden?: boolean, dropLevel?: number }>} */
export const CROPS = [
{{- range .Display}}
  { id: {{printf "%q" .Slug}}, name: {{printf "%q" .Name}}, unlock: {{.UnlockLevel}}, seedPrice: {{.SeedPrice}}, seasons: {{.Seasons}}, cycleMinutes: {{.CycleMinutes}}, cycleH: {{.CycleH}}, yield: {{.Yield}}, fruitPrice: {{.FruitPrice}}, harvestExp: {{.HarvestExp}}, body: {{printf "%q" .Body}}, color: {{printf "%q" .Color}}, fruit: {{.Fruit}}, leaf: {{.Leaf}}{{if .Hidden}}, hidden: true, dropLevel: {{.DropLevel}}{{end}} },
{{- end}}
];

/** @type {Record<number, string>} */
export const CROP_ID_TO_KEY = Object.freeze({
{{- range .ByID}}
  {{.ID}}: {{printf "%q" .Slug}},
{{- end}}
});

/** @type {Record<string, number>} */
export const CROP_KEY_TO_ID = Object.freeze({
{{- range .ByID}}
  {{.Slug}}: {{.ID}},
{{- end}}
});
`

type cropRow struct {
	ID           uint16
	Slug         string
	Name         string
	UnlockLevel  uint8
	SeedPrice    uint32
	Seasons      uint8
	CycleMinutes uint32
	CycleH       uint32 // CycleMinutes/60，仅展示
	Yield        uint16
	FruitPrice   uint32
	HarvestExp   uint32
	Hidden       bool
	DropLevel    uint8
	Body         string
	Color        string
	Fruit        string
	Leaf         string
}

type genData struct {
	Count   int
	Display []cropRow // CSV 行序
	ByID    []cropRow // ID 升序，长度 29，下标=id-1
}

func main() {
	root := flag.String("root", ".", "repository root")
	outGo := flag.String("out-go", "", "override Go output path")
	outJS := flag.String("out-js", "", "override JS output path")
	flag.Parse()

	csvPath := filepath.Join(*root, "config", "crops.csv")
	data, err := loadCrops(csvPath)
	if err != nil {
		fail(err)
	}

	goPath := *outGo
	if goPath == "" {
		goPath = filepath.Join(*root, "server", "shared", "gameconfig", "gen_crops.go")
	}
	jsPath := *outJS
	if jsPath == "" {
		jsPath = filepath.Join(*root, "client", "src", "game", "gen", "crops.js")
	}

	if err := writeGenerated(goPath, goHeader, data); err != nil {
		fail(err)
	}
	if err := writeGenerated(jsPath, jsHeader, data); err != nil {
		fail(err)
	}
	fmt.Printf("gen-config: wrote %d crops →\n  %s\n  %s\n", data.Count, goPath, jsPath)
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "gen-config: %v\n", err)
	os.Exit(1)
}

func loadCrops(path string) (genData, error) {
	f, err := os.Open(path)
	if err != nil {
		return genData{}, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.FieldsPerRecord = -1
	records, err := r.ReadAll()
	if err != nil {
		return genData{}, fmt.Errorf("read csv: %w", err)
	}
	if len(records) < 2 {
		return genData{}, fmt.Errorf("%s: need header + rows", path)
	}
	header := records[0]
	idx := map[string]int{}
	for i, h := range header {
		idx[strings.TrimSpace(h)] = i
	}
	required := []string{
		"id", "slug", "name", "unlock_level", "seed_price", "seasons", "cycle_minutes",
		"yield", "fruit_price", "harvest_exp", "hidden", "drop_level", "body", "color", "fruit", "leaf",
	}
	for _, key := range required {
		if _, ok := idx[key]; !ok {
			return genData{}, fmt.Errorf("%s: missing column %q", path, key)
		}
	}

	var display []cropRow
	seenID := map[uint16]string{}
	seenSlug := map[string]uint16{}
	for rowNum, rec := range records[1:] {
		line := rowNum + 2
		get := func(key string) string { return strings.TrimSpace(rec[idx[key]]) }
		id64, err := strconv.ParseUint(get("id"), 10, 16)
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: id: %w", path, line, err)
		}
		id := uint16(id64)
		if id == 0 {
			return genData{}, fmt.Errorf("%s:%d: id 0 reserved for empty crop", path, line)
		}
		slug := get("slug")
		if slug == "" {
			return genData{}, fmt.Errorf("%s:%d: empty slug", path, line)
		}
		if prev, ok := seenID[id]; ok {
			return genData{}, fmt.Errorf("%s:%d: duplicate id %d (also slug %q)", path, line, id, prev)
		}
		if prev, ok := seenSlug[slug]; ok {
			return genData{}, fmt.Errorf("%s:%d: duplicate slug %q (also id %d)", path, line, slug, prev)
		}
		seenID[id] = slug
		seenSlug[slug] = id

		unlock, err := parseU8(get("unlock_level"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: unlock_level: %w", path, line, err)
		}
		seedPrice, err := parseU32(get("seed_price"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: seed_price: %w", path, line, err)
		}
		seasons, err := parseU8(get("seasons"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: seasons: %w", path, line, err)
		}
		cycleMin, err := parseU32(get("cycle_minutes"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: cycle_minutes: %w", path, line, err)
		}
		if seasons > 1 {
			div := uint32(seasons) + 1
			if cycleMin%div != 0 {
				return genData{}, fmt.Errorf("%s:%d: cycle_minutes=%d not divisible by seasons+1=%d", path, line, cycleMin, div)
			}
		}
		if cycleMin%60 != 0 {
			return genData{}, fmt.Errorf("%s:%d: cycle_minutes=%d not divisible by 60 (cycleH display)", path, line, cycleMin)
		}
		yield, err := parseU16(get("yield"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: yield: %w", path, line, err)
		}
		fruitPrice, err := parseU32(get("fruit_price"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: fruit_price: %w", path, line, err)
		}
		harvestExp, err := parseU32(get("harvest_exp"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: harvest_exp: %w", path, line, err)
		}
		hidden, err := parseBool01(get("hidden"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: hidden: %w", path, line, err)
		}
		dropLevel, err := parseU8(get("drop_level"))
		if err != nil {
			return genData{}, fmt.Errorf("%s:%d: drop_level: %w", path, line, err)
		}
		display = append(display, cropRow{
			ID: id, Slug: slug, Name: get("name"), UnlockLevel: unlock, SeedPrice: seedPrice,
			Seasons: seasons, CycleMinutes: cycleMin, CycleH: cycleMin / 60,
			Yield: yield, FruitPrice: fruitPrice, HarvestExp: harvestExp,
			Hidden: hidden, DropLevel: dropLevel,
			Body: get("body"), Color: get("color"),
			Fruit: normalizeHexLiteral(get("fruit")), Leaf: normalizeHexLiteral(get("leaf")),
		})
	}
	if len(display) != 29 {
		return genData{}, fmt.Errorf("%s: got %d crops, want 29", path, len(display))
	}
	for id := uint16(1); id <= 29; id++ {
		if _, ok := seenID[id]; !ok {
			return genData{}, fmt.Errorf("%s: missing numeric id %d (set must be exactly 1..29)", path, id)
		}
	}

	byID := make([]cropRow, len(display))
	copy(byID, display)
	sort.Slice(byID, func(i, j int) bool { return byID[i].ID < byID[j].ID })
	for i, c := range byID {
		if c.ID != uint16(i+1) {
			return genData{}, fmt.Errorf("%s: after sort by id, index %d has id %d", path, i, c.ID)
		}
	}

	return genData{Count: 29, Display: display, ByID: byID}, nil
}

func parseU8(s string) (uint8, error) {
	v, err := strconv.ParseUint(s, 10, 8)
	return uint8(v), err
}

func parseU16(s string) (uint16, error) {
	v, err := strconv.ParseUint(s, 10, 16)
	return uint16(v), err
}

func parseU32(s string) (uint32, error) {
	v, err := strconv.ParseUint(s, 10, 32)
	return uint32(v), err
}

func parseBool01(s string) (bool, error) {
	switch s {
	case "0", "false", "FALSE":
		return false, nil
	case "1", "true", "TRUE":
		return true, nil
	default:
		return false, fmt.Errorf("want 0/1, got %q", s)
	}
}

func normalizeHexLiteral(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "0x") || strings.HasPrefix(s, "0X") {
		return "0x" + strings.ToLower(s[2:])
	}
	return s
}

func writeGenerated(path, tmplSrc string, data genData) error {
	tmpl, err := template.New("out").Parse(tmplSrc)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	out := bytes.TrimRight(buf.Bytes(), "\n")
	out = append(out, '\n')
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, out, 0o644)
}
