package farm

import "farm/server/internal/pkgerr"

const (
	stealCapNumerator   = 40
	stealCapDenominator = 100
	maxStealAmount      = 10
)

// StealAction carries the owner-side inputs for one resolved steal attempt.
// Roll is generated by the authoritative caller and must be in [1, 10].
type StealAction struct {
	VisitorUID uint64
	PlotIndex  uint8
	Roll       uint16
	Intercept  bool
}

// StealResult reports the fruit transferred from an owner's mature plot.
type StealResult struct {
	Err    pkgerr.Code
	CropID uint16
	Amount uint16
	Patch  ActionPatch
}

// ApplySteal advances then atomically validates and commits one steal attempt.
// Aggregate callers are serialized by their FarmActor, so StolenCount is a
// safe read-modify-write quota counter.
func (a *Aggregate) ApplySteal(action StealAction, now int64) StealResult {
	if a == nil {
		return StealResult{Err: pkgerr.Internal}
	}
	if action.VisitorUID == a.UID {
		return StealResult{Err: pkgerr.StealSelf}
	}
	if int(action.PlotIndex) >= int(a.UnlockedPlots) || int(action.PlotIndex) >= len(a.Plots) {
		return StealResult{Err: pkgerr.PlotNotFound}
	}
	if action.Roll == 0 || action.Roll > maxStealAmount {
		return StealResult{Err: pkgerr.BadRequest}
	}

	work := a.Plots[action.PlotIndex]
	advancePlot(&work, now)
	if work.State != StateMature {
		if work.State == StateResidue && work.HarvestRound > 0 {
			return StealResult{Err: pkgerr.HarvestedByOwner}
		}
		if work.State == StateWithered {
			return StealResult{Err: pkgerr.PlotWithered}
		}
		return StealResult{Err: pkgerr.PlotNotMature}
	}
	for _, uid := range work.Stealers {
		if uid == uint32(action.VisitorUID) {
			return StealResult{Err: pkgerr.StealAlreadyDone}
		}
	}

	cap := uint32(work.FinalYield) * stealCapNumerator / stealCapDenominator
	if uint32(work.StolenCount) >= cap {
		return StealResult{Err: pkgerr.StealQuotaExhausted}
	}
	remaining := cap - uint32(work.StolenCount)
	amount := uint32(action.Roll)
	if amount > remaining {
		amount = remaining
	}

	work.Stealers = append(work.Stealers, uint32(action.VisitorUID))
	if action.Intercept {
		a.Plots[action.PlotIndex] = work
		a.FarmSeq++
		return StealResult{
			Err:    pkgerr.StealIntercepted,
			CropID: work.CropID,
			Patch:  a.patchOf(action.PlotIndex),
		}
	}

	work.StolenCount += uint16(amount)
	a.Plots[action.PlotIndex] = work
	a.FarmSeq++

	return StealResult{
		Err:    pkgerr.OK,
		CropID: work.CropID,
		Amount: uint16(amount),
		Patch:  a.patchOf(action.PlotIndex),
	}
}

// HasStealable 报告是否仍存在「成熟且 40% 额度未耗尽」的地块（FriendList 弱摘要）。
func (a *Aggregate) HasStealable() bool {
	if a == nil {
		return false
	}
	limit := int(a.UnlockedPlots)
	if limit > len(a.Plots) {
		limit = len(a.Plots)
	}
	for i := 0; i < limit; i++ {
		p := a.Plots[i]
		if p.State != StateMature || p.FinalYield == 0 {
			continue
		}
		cap := uint32(p.FinalYield) * stealCapNumerator / stealCapDenominator
		if uint32(p.StolenCount) < cap {
			return true
		}
	}
	return false
}
