// Code generated by tools/gen-config; DO NOT EDIT.
// Source: config/crops.csv
package gameconf

// CropCount 是已登记作物种数（不含 ID 0）。
const CropCount = 29

// cropTable 按下标 id-1 存放，ID 集合恰为 1..CropCount。
var cropTable = []CropConf{
	{ID: 1, Slug: "bailuobo", Name: "白萝卜", UnlockLevel: 0, SeedPrice: 125, FruitPrice: 17, Yield: 16, Seasons: 1, CycleMinutes: 600, HarvestExp: 15, Hidden: false, DropLevel: 0},
	{ID: 2, Slug: "huluobo", Name: "胡萝卜", UnlockLevel: 0, SeedPrice: 163, FruitPrice: 21, Yield: 17, Seasons: 1, CycleMinutes: 780, HarvestExp: 18, Hidden: false, DropLevel: 0},
	{ID: 3, Slug: "dabaicai", Name: "大白菜", UnlockLevel: 1, SeedPrice: 168, FruitPrice: 22, Yield: 17, Seasons: 1, CycleMinutes: 840, HarvestExp: 19, Hidden: false, DropLevel: 0},
	{ID: 4, Slug: "pingguo", Name: "苹果", UnlockLevel: 10, SeedPrice: 578, FruitPrice: 24, Yield: 23, Seasons: 2, CycleMinutes: 1800, HarvestExp: 18, Hidden: false, DropLevel: 0},
	{ID: 5, Slug: "shuidao", Name: "水稻", UnlockLevel: 2, SeedPrice: 168, FruitPrice: 21, Yield: 18, Seasons: 1, CycleMinutes: 840, HarvestExp: 19, Hidden: false, DropLevel: 0},
	{ID: 6, Slug: "yumi", Name: "玉米", UnlockLevel: 3, SeedPrice: 175, FruitPrice: 23, Yield: 17, Seasons: 1, CycleMinutes: 840, HarvestExp: 19, Hidden: false, DropLevel: 0},
	{ID: 7, Slug: "tudou", Name: "土豆", UnlockLevel: 4, SeedPrice: 188, FruitPrice: 24, Yield: 18, Seasons: 1, CycleMinutes: 900, HarvestExp: 20, Hidden: false, DropLevel: 0},
	{ID: 8, Slug: "hongzao", Name: "红枣", UnlockLevel: 5, SeedPrice: 237, FruitPrice: 25, Yield: 20, Seasons: 1, CycleMinutes: 960, HarvestExp: 21, Hidden: false, DropLevel: 0},
	{ID: 9, Slug: "qiezi", Name: "茄子", UnlockLevel: 5, SeedPrice: 237, FruitPrice: 25, Yield: 20, Seasons: 1, CycleMinutes: 960, HarvestExp: 21, Hidden: false, DropLevel: 0},
	{ID: 10, Slug: "fanqie", Name: "番茄", UnlockLevel: 6, SeedPrice: 251, FruitPrice: 26, Yield: 21, Seasons: 1, CycleMinutes: 1020, HarvestExp: 22, Hidden: false, DropLevel: 0},
	{ID: 11, Slug: "wandou", Name: "豌豆", UnlockLevel: 7, SeedPrice: 266, FruitPrice: 27, Yield: 22, Seasons: 1, CycleMinutes: 1080, HarvestExp: 23, Hidden: false, DropLevel: 0},
	{ID: 12, Slug: "hongmeigui", Name: "红玫瑰", UnlockLevel: 7, SeedPrice: 266, FruitPrice: 27, Yield: 22, Seasons: 1, CycleMinutes: 1080, HarvestExp: 23, Hidden: false, DropLevel: 0},
	{ID: 13, Slug: "lajiao", Name: "辣椒", UnlockLevel: 8, SeedPrice: 296, FruitPrice: 28, Yield: 24, Seasons: 1, CycleMinutes: 1200, HarvestExp: 25, Hidden: false, DropLevel: 0},
	{ID: 14, Slug: "nangua", Name: "南瓜", UnlockLevel: 9, SeedPrice: 325, FruitPrice: 30, Yield: 25, Seasons: 1, CycleMinutes: 1320, HarvestExp: 27, Hidden: false, DropLevel: 0},
	{ID: 15, Slug: "xiaomai", Name: "小麦", UnlockLevel: 2, SeedPrice: 168, FruitPrice: 21, Yield: 18, Seasons: 1, CycleMinutes: 840, HarvestExp: 19, Hidden: false, DropLevel: 0},
	{ID: 16, Slug: "caomei", Name: "草莓", UnlockLevel: 10, SeedPrice: 605, FruitPrice: 27, Yield: 24, Seasons: 2, CycleMinutes: 2100, HarvestExp: 20, Hidden: false, DropLevel: 0},
	{ID: 17, Slug: "xigua", Name: "西瓜", UnlockLevel: 11, SeedPrice: 708, FruitPrice: 29, Yield: 27, Seasons: 2, CycleMinutes: 2460, HarvestExp: 23, Hidden: false, DropLevel: 0},
	{ID: 18, Slug: "xiangjiao", Name: "香蕉", UnlockLevel: 12, SeedPrice: 900, FruitPrice: 32, Yield: 29, Seasons: 2, CycleMinutes: 2700, HarvestExp: 25, Hidden: false, DropLevel: 0},
	{ID: 19, Slug: "taozi", Name: "桃子", UnlockLevel: 13, SeedPrice: 1200, FruitPrice: 40, Yield: 32, Seasons: 2, CycleMinutes: 3600, HarvestExp: 33, Hidden: false, DropLevel: 0},
	{ID: 20, Slug: "chengzi", Name: "橙子", UnlockLevel: 14, SeedPrice: 1587, FruitPrice: 41, Yield: 26, Seasons: 3, CycleMinutes: 3540, HarvestExp: 25, Hidden: false, DropLevel: 0},
	{ID: 21, Slug: "putao", Name: "葡萄", UnlockLevel: 15, SeedPrice: 1978, FruitPrice: 47, Yield: 29, Seasons: 3, CycleMinutes: 5160, HarvestExp: 30, Hidden: false, DropLevel: 0},
	{ID: 22, Slug: "shiliu", Name: "石榴", UnlockLevel: 16, SeedPrice: 2425, FruitPrice: 54, Yield: 30, Seasons: 3, CycleMinutes: 5760, HarvestExp: 34, Hidden: false, DropLevel: 0},
	{ID: 23, Slug: "youzi", Name: "柚子", UnlockLevel: 17, SeedPrice: 2855, FruitPrice: 58, Yield: 33, Seasons: 3, CycleMinutes: 6780, HarvestExp: 39, Hidden: false, DropLevel: 0},
	{ID: 24, Slug: "boluo", Name: "菠萝", UnlockLevel: 18, SeedPrice: 3480, FruitPrice: 62, Yield: 35, Seasons: 3, CycleMinutes: 6960, HarvestExp: 40, Hidden: false, DropLevel: 0},
	{ID: 25, Slug: "yezi", Name: "椰子", UnlockLevel: 19, SeedPrice: 3720, FruitPrice: 65, Yield: 27, Seasons: 4, CycleMinutes: 7440, HarvestExp: 32, Hidden: false, DropLevel: 0},
	{ID: 26, Slug: "hulu", Name: "葫芦", UnlockLevel: 20, SeedPrice: 4742, FruitPrice: 71, Yield: 30, Seasons: 4, CycleMinutes: 8340, HarvestExp: 36, Hidden: false, DropLevel: 0},
	{ID: 27, Slug: "renshen", Name: "人参", UnlockLevel: 0, SeedPrice: 0, FruitPrice: 41, Yield: 22, Seasons: 1, CycleMinutes: 2400, HarvestExp: 60, Hidden: true, DropLevel: 0},
	{ID: 28, Slug: "lingzhi", Name: "灵芝", UnlockLevel: 10, SeedPrice: 0, FruitPrice: 60, Yield: 30, Seasons: 1, CycleMinutes: 3600, HarvestExp: 80, Hidden: true, DropLevel: 10},
	{ID: 29, Slug: "yaoqianshu", Name: "摇钱树", UnlockLevel: 20, SeedPrice: 0, FruitPrice: 55, Yield: 25, Seasons: 3, CycleMinutes: 6000, HarvestExp: 100, Hidden: true, DropLevel: 20},
}
