FROM grafana/grafana:11.2.0
COPY --chown=472:0 deploy/observability/grafana/provisioning /etc/grafana/provisioning
COPY --chown=472:0 deploy/observability/grafana/dashboards /var/lib/grafana/dashboards
